// Dynamic javascript file generated by OPEN BEXI HTML Builder version 2.0 beta
var _CURRENT_OPENBEXI_LANGUAGE = "en";
var openbexi_webPages = [
        ['Select a web page'],
        ['index.html'],
        ['index_fr.html'],
        ['ob_demo1.html'],
        ['Select a web page.html'],
        ['no_name.html'],
        ['Create a new page.html'],
        ['no_name4.html'],
        ['no_name2.html'],
        ['no_name1.html'],
        ['template1.html'],
        ['no_name .html'],
        ['no_name3.html'],
        ['open_bexi_page_under_construction_page.html'],
        ['open_bexi_page_under_construction_form.html']];

